name = "EasyMLClasses"
uuid = "5a06b745-583a-4b87-a77e-c5c0cb1b0310"
authors = ["Open Machine Learning Association <a_ill@outlook.com>"]
version = "0.1.0"

[deps]
EasyMLCore = "36e2bb64-004e-43a5-86c1-8a670a7c5030"
FluxExtra = "81ebe36b-92a1-4b50-bd7a-fa963d2933c8"

[compat]
julia = "1.6"
