name: CI main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags: '*'
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@v1
      - if: ${{ matrix.os == 'macOS-latest' ||  matrix.os  == 'windows-latest' }}
        uses: julia-actions/julia-runtest@v1
      - name: Run julia-actions/julia-runtest@v1 ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get install xvfb libxkbcommon-x11-0
          xvfb-run --auto-servernum julia --color=yes --check-bounds=yes --project -e 'using Pkg; Pkg.test(coverage=true)'
        env:
          XDG_RUNTIME_DIR: /tmp/runtime-runner
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info